import React from 'react';
import { ProviderConfig } from '../types';
import { 
  VercelLogoSVG, 
  RenderLogoSVG, 
  RailwayLogoSVG, 
  DOLogoSVG, 
  FlyLogoSVG, 
  CoolifyLogoSVG,
  AWSLogo
} from './providerLogos';

export const PROVIDER_CONFIGS: Record<string, ProviderConfig> = {
  Vercel: {
    key: 'vercel', label: 'Vercel',
    tokenLabel: 'Vercel Personal Access Token', placeholder: 'vk1_xxxxxxxxxxxxxxxx',
    tokenPageUrl: 'https://vercel.com/account/tokens', tokenPageLabel: 'Open Vercel Tokens Page',
    description: 'Enter your Vercel Personal Access Token to enable deployment monitoring and project analytics.',
    guideTitle: 'How to generate your Vercel token',
    guideSubtitle: 'Follow these steps to create a Personal Access Token from your Vercel dashboard. This token gives ServX read-only access to your deployments and projects.',
    steps: [
      { title: 'Open Account Settings', detail: 'Click your profile picture in the top-right corner of Vercel, then select Account Settings.' },
      { title: 'Navigate to Tokens', detail: 'In the left sidebar, click Tokens to open the token management page.' },
      { title: 'Create a new token', detail: 'Click Create, name it "Orizon Dashboard", and copy the generated token (e.g., vk1_...).' },
    ],
    features: ['AES-256 encrypted', 'Real-time deployment sync', 'Multi-project support'],
    logo: <VercelLogoSVG className="w-12 h-12" />,
    logoSmall: <VercelLogoSVG />,
  },
  Render: {
    key: 'render', label: 'Render',
    tokenLabel: 'Render API Key', placeholder: 'rnd_xxxxxxxxxxxxxxxx',
    tokenPageUrl: 'https://dashboard.render.com/u/settings#api-keys', tokenPageLabel: 'Open Render API Keys Page',
    description: 'Enter your Render API Key to enable service monitoring, deployment tracking, and resource analytics.',
    guideTitle: 'How to generate your Render API Key',
    guideSubtitle: 'Follow these steps to create an API Key from your Render dashboard. This key gives ServX access to your services and deployments.',
    steps: [
      { title: 'Open Account Settings', detail: 'Click your profile in the top right of the Render Dashboard and select Account Settings.' },
      { title: 'Navigate to API Keys', detail: 'Click API Keys in the left sidebar menu.' },
      { title: 'Create API Key', detail: 'Click Create API Key, name it "ServX", and paste the rnd_... token here.' },
    ],
    features: ['AES-256 encrypted', 'Service health monitoring', 'Deploy history tracking'],
    logo: <RenderLogoSVG className="w-12 h-12" />,
    logoSmall: <RenderLogoSVG />,
  },
  Railway: {
    key: 'railway', label: 'Railway',
    tokenLabel: 'Railway API Token', placeholder: 'railway_xxxxxxxxxxxxxxxx',
    tokenPageUrl: 'https://railway.app/account/tokens', tokenPageLabel: 'Open Railway Tokens Page',
    description: 'Enter your Railway API Token to enable project monitoring and deployment analytics.',
    guideTitle: 'How to generate your Railway token',
    guideSubtitle: 'Follow these steps to create an API Token from your Railway account. This token gives Orizon read access to your projects and services.',
    steps: [
      { title: 'Open Account Settings', detail: 'Click your avatar in the bottom-left of Railway, then select Account Settings.' },
      { title: 'Navigate to Tokens', detail: 'Click the Tokens tab to open the API token management page.' },
      { title: 'Create a new token', detail: 'Click Create Token, name it "ServX Dashboard", copy the generated token.' },
    ],
    features: ['AES-256 encrypted', 'Project monitoring', 'GraphQL-powered sync'],
    logo: <RailwayLogoSVG className="w-12 h-12" />,
    logoSmall: <RailwayLogoSVG />,
  },
  DigitalOcean: {
    key: 'digitalocean', label: 'DigitalOcean',
    tokenLabel: 'DigitalOcean Personal Access Token', placeholder: 'dop_v1_xxxxxxxxxxxxxxxx',
    tokenPageUrl: 'https://cloud.digitalocean.com/account/api/tokens', tokenPageLabel: 'Open DigitalOcean API Tokens',
    description: 'Enter your DigitalOcean Personal Access Token to monitor Apps, Droplets, and Kubernetes clusters.',
    guideTitle: 'How to generate your DigitalOcean token',
    guideSubtitle: 'Follow these steps to create a Personal Access Token from the DigitalOcean cloud console.',
    steps: [
      { title: 'Open API Settings', detail: 'In the DigitalOcean dashboard, click API in the left sidebar (under Account).' },
      { title: 'Generate Token', detail: 'Under Personal access tokens, click Generate New Token.' },
      { title: 'Configure & Copy', detail: 'Name it "Orizon Dashboard", select Read scope, click Generate Token, then copy the dop_v1_... value.' },
    ],
    features: ['AES-256 encrypted', 'App Platform monitoring', 'Droplet analytics'],
    logo: <DOLogoSVG className="w-12 h-12" />,
    logoSmall: <DOLogoSVG />,
  },
  'Fly.io': {
    key: 'fly', label: 'Fly.io',
    tokenLabel: 'Fly.io Auth Token', placeholder: 'FlyV1_xxxxxxxxxxxxxxxx',
    tokenPageUrl: 'https://fly.io/user/personal_access_tokens', tokenPageLabel: 'Open Fly.io Tokens Page',
    description: 'Enter your Fly.io Auth Token to monitor your applications and machines.',
    guideTitle: 'How to generate your Fly.io token',
    guideSubtitle: 'Follow these steps to create a Personal Access Token from your Fly.io dashboard.',
    steps: [
      { title: 'Open Account Settings', detail: 'Go to fly.io, click your avatar in the top right, and select Account.' },
      { title: 'Navigate to Access Tokens', detail: 'In the sidebar, click Access Tokens under Personal.' },
      { title: 'Create Token', detail: 'Click Create Access Token, name it "ServX Dashboard", and copy the generated value.' },
    ],
    features: ['AES-256 encrypted', 'Machine monitoring', 'Multi-region support'],
    logo: <FlyLogoSVG className="w-12 h-12" />,
    logoSmall: <FlyLogoSVG />,
  },
  AWS: {
    key: 'aws', label: 'AWS',
    tokenLabel: 'AWS Access Key ID : Secret', placeholder: 'AKIA...:wJalrX...',
    tokenPageUrl: 'https://us-east-1.console.aws.amazon.com/iam/home#/security_credentials', tokenPageLabel: 'Open AWS Security Credentials',
    description: 'Enter your AWS Access Key to monitor EC2 instances, Lambda functions, and ECS services.',
    guideTitle: 'How to generate your AWS credentials',
    guideSubtitle: 'Follow these steps to create Access Keys from the AWS IAM console. We recommend a read-only IAM user.',
    steps: [
      { title: 'Open IAM Console', detail: 'Sign in to AWS, search for IAM, and navigate to Users or Security Credentials.' },
      { title: 'Create Access Key', detail: 'Under Access keys, click Create access key. Select "Third-party service" use case.' },
      { title: 'Copy Credentials', detail: 'Copy both the Access Key ID and Secret Access Key. Paste them here as AKIAXXXX:SecretKeyHere.' },
    ],
    features: ['AES-256 encrypted', 'EC2 & Lambda monitoring', 'Multi-service support'],
    logo: <AWSLogo className="w-12 h-12" />,
    logoSmall: <AWSLogo />,
  },
  Coolify: {
    key: 'coolify', label: 'Coolify',
    tokenLabel: 'Coolify API Token', placeholder: 'Enter API Bearer Token',
    tokenPageUrl: '', tokenPageLabel: 'Open Coolify Settings',
    description: 'Enter your Coolify Instance URL and API Token to monitor your self-hosted projects and servers.',
    guideTitle: 'How to connect your Coolify instance',
    guideSubtitle: 'Follow these steps to generate an API key from your self-hosted Coolify dashboard.',
    steps: [
      { title: 'Open Settings', detail: 'Log in to your Coolify instance and navigate to the Settings page.' },
      { title: 'Generate API Key', detail: 'Go to the API Keys section and create a new key named "Orizon".' },
      { title: 'Copy Information', detail: 'Copy the API key and ensure you know your instance URL (e.g., https://app.coolify.io).' },
    ],
    features: ['Self-hosted support', 'Real-time resource sync', 'AES-256 encrypted'],
    logo: <CoolifyLogoSVG className="w-12 h-12" />,
    logoSmall: <CoolifyLogoSVG />,
  },
};
